version: '3'
services:
  front-react:
    build:
      context: ./client

    environment:
      NODE_ENV: development
    depends_on:
      - server-dev
    volumes:
      - ./client:/client
      - /client/node_modules
    ports:
      - '5000:3000'

  server-dev:
    build:
      context: ./server
    depends_on:
      - db-dev
      - mongo-dev
    restart: always
    environment:
      NODE_ENV: development
    ports:
      - '3000:3000'
    
    volumes:
      - ./var/www/html/images:/var/www/html/images
      - ./server:/server
      - /server/node_modules
    

  mongo-dev:
    image: mongo:4.4.6-bionic
    ports:
      - '27018:27017'

  db-dev:
    image: postgres:13.2-alpine
    restart: on-failure
    environment:   
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: squadhelp-d
    ports:
      - '2345:5432'

volumes:
  server-dev: