GET http://localhost:5000/user/id/transactions 
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdE5hbWUiOiJDcmVhdG9yIiwidXNlcklkIjoyLCJyb2xlIjoiY3JlYXRvciIsImxhc3ROYW1lIjoiQ3JlYXRvciIsImF2YXRhciI6ImFub24ucG5nIiwiZGlzcGxheU5hbWUiOiJDUkVBVE9SIiwiYmFsYW5jZSI6IjUwIiwiZW1haWwiOiJjcmVhdG9yQGdtYWlsLmNvbSIsInJhdGluZyI6NC41LCJpYXQiOjE2OTQxMTQxOTAsImV4cCI6MTY5NDExNzc5MH0.cI9AjOYi0NwAr6AXGAV0K8GwBllq7tjXGAtIZk9ECHQ